{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-test",
    "version": "2.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "kimql5ndvbejrlprsu4az6mwfy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.4.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "2.4.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test-autoconfigure",
          "version": {
            "requires": "2.4.4"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "2.3.3"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.18.1"
          }
        },
        {
          "group": "org.hamcrest",
          "module": "hamcrest",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.6.28"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "3.6.28"
          }
        },
        {
          "group": "org.skyscreamer",
          "module": "jsonassert",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "5.3.5"
          }
        },
        {
          "group": "org.xmlunit",
          "module": "xmlunit-core",
          "version": {
            "requires": "2.7.0"
          },
          "excludes": [
            {
              "group": "javax.xml.bind",
              "module": "jaxb-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-test-2.4.4.jar",
          "url": "spring-boot-starter-test-2.4.4.jar",
          "size": 4793,
          "sha512": "8ccc4f011e1dcb056355bdcde0969a13334809da94a5925cdff51f14ee84fe30a6397304c656d2c06f0baa60a813168c4ca903efccc708a79a6289359b3dcd70",
          "sha256": "5f94c817e3322badf5ce3985fa194da0966cace677d88a5259db28f18f75826f",
          "sha1": "bf35adef93978c3e8458e4e12a3c220641e8b461",
          "md5": "fe84062fafc1075091d6a5b09190c57e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.4.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "2.4.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test-autoconfigure",
          "version": {
            "requires": "2.4.4"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "2.3.3"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.18.1"
          }
        },
        {
          "group": "org.hamcrest",
          "module": "hamcrest",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.6.28"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "3.6.28"
          }
        },
        {
          "group": "org.skyscreamer",
          "module": "jsonassert",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "5.3.5"
          }
        },
        {
          "group": "org.xmlunit",
          "module": "xmlunit-core",
          "version": {
            "requires": "2.7.0"
          },
          "excludes": [
            {
              "group": "javax.xml.bind",
              "module": "jaxb-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-test-2.4.4.jar",
          "url": "spring-boot-starter-test-2.4.4.jar",
          "size": 4793,
          "sha512": "8ccc4f011e1dcb056355bdcde0969a13334809da94a5925cdff51f14ee84fe30a6397304c656d2c06f0baa60a813168c4ca903efccc708a79a6289359b3dcd70",
          "sha256": "5f94c817e3322badf5ce3985fa194da0966cace677d88a5259db28f18f75826f",
          "sha1": "bf35adef93978c3e8458e4e12a3c220641e8b461",
          "md5": "fe84062fafc1075091d6a5b09190c57e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-test-2.4.4-javadoc.jar",
          "url": "spring-boot-starter-test-2.4.4-javadoc.jar",
          "size": 4744,
          "sha512": "34cc77ffa683d40ce29e0ecc7ffa317d2d0858fc7adb8c166c8a030190f3233ff4f519db5022a7d914921755d7c0f099b17fef75059d3c19884982b34547cf00",
          "sha256": "7b4359ef75a193f41fbf986434e67cdf7f4c66e749809b169362d6e240b41780",
          "sha1": "4c8ba87369bb7cc0495c3ea569e70c9eb50d1a72",
          "md5": "3da7415231cc214869e1b9420c3a0417"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-test-2.4.4-sources.jar",
          "url": "spring-boot-starter-test-2.4.4-sources.jar",
          "size": 4742,
          "sha512": "10f93ce8b1c6bfceb6250100ae3c80286b688de45d6d0297c916a15643e16c514c88ba485e2cfda8f7a6c09163fd8a20975f2723f01c7e790282331ee9cff1bf",
          "sha256": "ac04240beacfdd185cd7da9c6f51b41e47acde0ed94e09ba0a8a5c2000fdd078",
          "sha1": "eef197a713a2014ae7a626b033fe3f3fae3fc4cc",
          "md5": "d4ec586855acc41ecebd63d1bf3235b0"
        }
      ]
    }
  ]
}
