{
  "formatVersion": "1.1",
  "component": {
    "group": "org.junit.jupiter",
    "module": "junit-jupiter-api",
    "version": "5.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "xrgizuntbnaa5ldju7zisp5uqi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.7.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.apiguardian",
          "module": "apiguardian-api",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.opentest4j",
          "module": "opentest4j",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-commons",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "junit-jupiter-api-5.7.1.jar",
          "url": "junit-jupiter-api-5.7.1.jar",
          "size": 175588,
          "sha512": "21b90d5887da45eed3739fe2728a483cf39d0ea13dbad4529a7e561f964f5d870b859bdc038efba3d7102013bf1b74d638eb471fcd3f915e1cc4e35f989f179c",
          "sha256": "ce7b985bc469e2625759a4ebc45533c70581a05a348278c1d6408e9b2e35e314",
          "sha1": "a7261dff44e64aea7f621842eac5977fd6d2412d",
          "md5": "69395a5e457e37765d4fbbbb5f2d5a18"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.7.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.apiguardian",
          "module": "apiguardian-api",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.opentest4j",
          "module": "opentest4j",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-commons",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "junit-jupiter-api-5.7.1.jar",
          "url": "junit-jupiter-api-5.7.1.jar",
          "size": 175588,
          "sha512": "21b90d5887da45eed3739fe2728a483cf39d0ea13dbad4529a7e561f964f5d870b859bdc038efba3d7102013bf1b74d638eb471fcd3f915e1cc4e35f989f179c",
          "sha256": "ce7b985bc469e2625759a4ebc45533c70581a05a348278c1d6408e9b2e35e314",
          "sha1": "a7261dff44e64aea7f621842eac5977fd6d2412d",
          "md5": "69395a5e457e37765d4fbbbb5f2d5a18"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-jupiter-api-5.7.1-javadoc.jar",
          "url": "junit-jupiter-api-5.7.1-javadoc.jar",
          "size": 1011886,
          "sha512": "d3c8b271ad1498c2272cf7781999861523c8080c0d22d8999e5047ffb386f37d824572ee4576eee87f850c038c4389f8b420711a5b35d4b14cb37e75d24d3231",
          "sha256": "e28edb5aa838b10c21080784ec5024683a1452b8c494c3f4cfb6befbae57ace1",
          "sha1": "dda62903b0eb2b9aa7232c899aa7d2125e532af7",
          "md5": "6691ebe597f8a5c25b40fa3c92870fea"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-jupiter-api-5.7.1-sources.jar",
          "url": "junit-jupiter-api-5.7.1-sources.jar",
          "size": 173663,
          "sha512": "59b1f99e8db272c166093a7ff0c7b9227d942c23fd552a05f89b6a90f785fd0869ceabc3a5f5048ebc8afe424094efbda151c77af256ac982acd9468959b2414",
          "sha256": "6c18062cf4ad21f08702e94f3004110aa1c23fff94052f73a75ac2193444f503",
          "sha1": "ebca04edd1975a8fd42846c4f6d0b8fec3d6efc1",
          "md5": "b97aeb68097fdbb15ee79c2a13e593fb"
        }
      ]
    }
  ]
}
